"""Уровень A2: 1000 самых частотных слов английского языка."""

from .a1 import A1_WORDS

A2_WORDS = A1_WORDS + [
    # 301-1000: Расширенный словарь
    "about", "above", "across", "act", "active", "activity", "add", "address", "adult", "advice",
    "afford", "afraid", "after", "again", "against", "age", "ago", "agree", "ahead",
    "allow", "already", "although", "among", "amount", "ancient", "angry", "animal", "announce",
    "anyone", "anything", "anywhere", "appear", "apply", "approach", "area", "argue", "arise",
    "around", "arrange", "arrive", "artist", "aspect", "assess", "assign", "assist", "assume",
    "atmosphere", "attach", "attempt", "attend", "attention", "attract", "audience", "author",
    "available", "avoid", "award", "aware", "background", "balance", "basis", "battle", "beat",
    "behind", "belong", "beneath", "benefit", "beside", "beyond", "billion", "bind", "blame",
    "board", "bother", "bottle", "bottom", "bound", "brain", "branch", "brand",
    "breakthrough", "breed", "bridge", "brief", "bring", "broad", "build", "burn", "busy",
    "capable", "capture", "career", "central", "century", "certain", "challenge", "change",
    "character", "charge", "cheap", "check", "choice", "choose", "church", "citizen", "civil",
    "claim", "clear", "climate", "close", "coach", "coast", "color", "combat", "combine",
    "comfort", "command", "common", "company", "compare", "compete", "complain", "complex",
    "concept", "concern", "conduct", "confident", "confirm", "conflict", "confuse", "connect",
    "conscious", "conservative", "consider", "consist", "consult", "contain", "continue",
    "contract", "contribute", "control", "convince", "create", "credit", "crime", "crisis",
    "critical", "cross", "crowd", "crucial", "culture", "current", "daily", "damage", "danger",
    "deal", "debate", "decade", "defend", "define", "demand", "department", "depend", "derive",
    "deserve", "desire", "detail", "detect", "determine", "develop", "device", "devote",
    "different", "direct", "discuss", "disease", "display", "distance", "distinguish", "distribute",
    "district", "diverse", "document", "domestic", "dominant", "doubt", "draft", "dramatic",
    "draw", "drink", "drive", "drop", "due", "duration", "duty", "dynamic", "eager", "earn",
    "economy", "edge", "effective", "effort", "elaborate", "eliminate", "else", "emerge", "emotion",
    "employ", "enable", "encounter", "encourage", "enormous", "ensure", "entire", "entry",
    "environment", "equal", "establish", "estimate", "evaluate", "even", "event", "evolve",
    "examine", "exceed", "except", "exchange", "exclude", "execute", "exercise", "exist",
    "expand", "expect", "expert", "expose", "express", "extend", "extensive", "external",
    "extra", "extreme", "facility", "factor", "failure", "fair", "faith", "fashion", "favor",
    "fear", "feature", "federal", "fee", "fellow", "female", "figure", "final", "finance",
    "firm", "fix", "flesh", "float", "floor", "flow", "focus", "follow", "force", "foreign",
    "forest", "forget", "form", "formal", "former", "found", "foundation", "freedom", "frequent",
    "friend", "front", "fuel", "function", "fund", "future", "gain", "gap", "gather", "gender",
    "generate", "gift", "global", "goal", "govern", "grant", "grateful", "gross", "ground",
    "group", "growth", "guarantee", "guard", "guess", "guide", "guilty", "habitat", "half",
    "handle", "happen", "hardly", "harm", "health", "heavy", "hidden", "highlight",
    "hire", "hobby", "honor", "huge", "human", "humor", "hurt", "ideal",
    "ignore", "ill", "image", "immediate", "impact", "implement", "imply", "import", "impose",
    "impress", "improve", "include", "increase", "independent", "indicate", "individual", "industry",
    "inevitable", "influence", "initial", "innovate", "insist", "inspect", "inspire", "install",
    "intelligent", "intend", "interest", "interpret", "interrupt", "investigate", "involve", "issue",
    "join", "junior", "justice", "justify", "keen", "keep", "key", "kill", "lack", "latter",
    "launch", "lay", "lead", "leap", "leg", "legal", "lend", "level", "liberal", "lift",
    "light", "limited", "link", "list", "literature", "local", "locate", "logic", "loose",
    "lower", "luck", "main", "major", "male", "manage", "manner", "manufacture", "mark", "market",
    "master", "match", "material", "matter", "mayor", "meaning", "measure", "medical", "medium",
    "mental", "merely", "method", "military", "million", "minor", "minute", "mission", "model",
    "moderate", "modify", "monitor", "moral", "moreover", "mostly", "motor", "move", "multiple",
    "muscle", "musical", "mutual", "narrow", "nation", "nature", "nearby", "necessary", "negative",
    "neither", "nevertheless", "normal", "note", "notion", "novel", "numerous", "nurse", "obtain",
    "obvious", "occasion", "occupy", "occur", "odd", "offer", "official", "operate", "opinion",
    "oppose", "option", "ordinary", "organize", "origin", "outcome", "outer", "output", "outside",
    "overall", "overcome", "overlook", "own", "pace", "pain", "panic", "participate", "particular",
    "party", "patient", "pattern", "pause", "peace", "perceive", "perform", "perhaps", "persist",
    "personal", "persuade", "phase", "phenomenon", "physical", "pick", "pilot", "pioneer", "plain",
    "plan", "plant", "platform", "pleasant", "pledge", "plenty", "policy", "political", "poor",
    "popular", "portion", "positive", "possible", "post", "potential", "poverty", "power", "practice",
    "precious", "predict", "prefer", "premise", "prepare", "press", "pressure", "prevent", "previous",
    "price", "primary", "prime", "principal", "principle", "priority", "private", "probably",
    "process", "produce", "professional", "profit", "program", "progress", "project", "prominent",
    "promise", "promote", "propose", "protect", "protest", "prove", "provide", "publish", "purchase",
    "pursue", "qualify", "quarter", "quiet", "radical", "raise", "random", "range", "rapid",
    "rare", "rate", "reach", "react", "read", "real", "realize", "reasonable", "recall", "receive",
    "recent", "recognize", "recommend", "record", "recruit", "reduce", "refer", "reflect", "reform",
    "regard", "regional", "regulate", "reinforce", "reject", "relate", "relative", "release",
    "relevant", "relief", "religion", "remain", "remedy", "remote", "remove", "replace", "reply",
    "report", "represent", "reproduce", "request", "require", "research", "resolve", "resort",
    "resource", "respond", "restore", "restrict", "retain", "reveal", "revolution", "reward",
    "rid", "rise", "risk", "role", "rough", "route", "routine", "rule", "run", "sacrifice",
    "safety", "salary", "sample", "scale", "scene", "schedule", "scholar", "science", "scope",
    "score", "season", "secure", "seek", "select", "senior", "sense", "sensitive", "separate",
    "sequence", "serve", "session", "settle", "shelter", "shift", "ship", "shock", "short",
    "shoulder", "signal", "significant", "silence", "silly", "similar", "simple", "site", "situation",
    "skill", "smooth", "social", "solely", "solve", "somewhat", "source", "special", "species",
    "specific", "speech", "spirit", "spite", "split", "spread", "stable", "staff", "stage",
    "stake", "standard", "status", "steady", "stick", "still", "stimulate", "stock", "strain",
    "strategy", "strength", "stress", "stretch", "strict", "strike", "string", "strong", "structure",
    "struggle", "style", "subjective", "submit", "substance", "succeed", "sufficient", "summer",
    "supply", "support", "suppose", "supreme", "surface", "surplus", "survive", "suspect",
    "suspend", "sustain", "switch", "symbol", "system", "tackle", "target", "task", "technique",
    "technology", "temperature", "temporary", "tend", "tendency", "tense", "theory", "thorough",
    "threat", "throughout", "thus", "tight", "tiny", "tool", "topic", "total", "touch", "tough",
    "tour", "tower", "track", "trade", "traffic", "train", "transfer", "transform", "transition",
    "transport", "travel", "treat", "tremendous", "trend", "trial", "tribe", "troop", "trouble",
    "unique", "unit", "universe", "urban", "urge", "useful", "utter", "various", "venture",
    "version", "victim", "victory", "view", "violate", "virtual", "visible", "vision", "visit",
    "vital", "volume", "vote", "wage", "warn", "welfare", "widespread", "wild", "win", "wind",
    "wise", "withdraw", "witness", "wonder", "wood", "worth", "wound", "writer", "young", "youth"
]
