"""Уровень B1: 3000 самых частотных слов английского языка."""

from .a2 import A2_WORDS

B1_WORDS = A2_WORDS + [
    # 1001-3000: Продвинутый словарь
    "abandon", "abuse", "academic", "academy", "accelerate", "access", "accommodate", "accompany",
    "accomplish", "accuse", "achieve", "acknowledge", "acquire", "adapt", "adequate", "adjust",
    "adopt", "advance", "advantage", "adversary", "advertise", "advocate", "affect", "aggregate",
    "aggressive", "allege", "allocate", "alternative", "amaze", "analyze", "annual", "anticipate",
    "anxiety", "apparent", "appeal", "appreciate", "approve", "arrange", "artificial", "assemble",
    "asset", "associate", "assure", "attain", "attitude", "attract", "awareness", "awkward",
    "bargain", "behalf", "behavior", "beneficial", "betray", "bias", "bitter", "blossom",
    "boost", "boundary", "breakdown", "briefly", "budget", "calculate", "candidate", "capable",
    "celebrate", "challenge", "chaos", "charity", "charm", "cheer", "circumstance", "civilian",
    "classify", "coincide", "collapse", "combine", "commerce", "commission", "commit", "communicate",
    "community", "compel", "compensate", "compete", "complement", "compliment", "comprehensive",
    "compromise", "concentrate", "confess", "confront", "confuse", "consequence", "conservation",
    "conservative", "considerable", "consist", "consistent", "constitute", "consult", "consume",
    "contemporary", "contradict", "contribute", "controversial", "convenient", "convince",
    "cooperate", "correspond", "counsel", "courage", "creative", "crisis", "criterion", "crucial",
    "cultivate", "curiosity", "database", "dedicate", "defeat", "defend", "definitive", "delay",
    "delicate", "deliver", "demand", "demolish", "deprive", "deserve", "design", "desperate",
    "detect", "determination", "devote", "dignity", "dimension", "discipline", "discount",
    "discrimination", "dispatch", "disperse", "display", "dispute", "diverse", "domestic",
    "dominate", "draft", "dramatic", "duration", "eager", "economy", "edge", "effective",
    "effort", "elaborate", "eliminate", "emerge", "emotion", "employ", "enable", "encounter",
    "encourage", "enormous", "ensure", "entire", "entry", "environment", "equal", "establish",
    "estimate", "evaluate", "event", "evolve", "examine", "exceed", "exchange", "exclude",
    "execute", "exercise", "exist", "expand", "expect", "expert", "expose", "express", "extend",
    "extensive", "external", "extra", "extreme", "facility", "factor", "failure", "fair",
    "faith", "fashion", "favor", "fear", "feature", "federal", "fee", "fellow", "female",
    "figure", "final", "finance", "firm", "fix", "flesh", "float", "floor", "flow", "focus",
    "follow", "force", "foreign", "forest", "forget", "form", "formal", "former", "found",
    "foundation", "freedom", "frequent", "friend", "front", "fuel", "function", "fund", "future",
    "gain", "gap", "gather", "gender", "generate", "gift", "global", "goal", "govern", "grant",
    "grateful", "gross", "ground", "group", "growth", "guarantee", "guard", "guess", "guide",
    "guilty", "habitat", "half", "handle", "happen", "hardly", "harm", "health", "heavy",
    "hidden", "highlight", "hire", "hobby", "honor", "huge", "human", "humor", "hurt",
    "ideal", "ignore", "ill", "image", "immediate", "impact", "implement", "imply",
    "import", "impose", "impress", "improve", "include", "increase", "independent", "indicate",
    "individual", "industry", "inevitable", "influence", "initial", "innovate", "insist",
    "inspect", "inspire", "install", "intelligent", "intend", "interest", "interpret", "interrupt",
    "investigate", "involve", "issue", "join", "junior", "justice", "justify", "keen", "keep",
    "key", "kill", "lack", "latter", "launch", "lay", "lead", "leap", "leg", "legal", "lend",
    "level", "liberal", "lift", "light", "limited", "link", "list", "literature", "local",
    "locate", "logic", "loose", "lower", "luck", "main", "major", "male", "manage", "manner",
    "manufacture", "mark", "market", "master", "match", "material", "matter", "mayor", "meaning",
    "measure", "medical", "medium", "mental", "merely", "method", "military", "million", "minor",
    "minute", "mission", "model", "moderate", "modify", "monitor", "moral", "moreover", "mostly",
    "motor", "move", "multiple", "muscle", "musical", "mutual", "narrow", "nation", "nature",
    "nearby", "necessary", "negative", "neither", "nevertheless", "normal", "note", "notion",
    "novel", "numerous", "nurse", "obtain", "obvious", "occasion", "occupy", "occur", "odd",
    "offer", "official", "operate", "opinion", "oppose", "option", "ordinary", "organize",
    "origin", "outcome", "outer", "output", "outside", "overall", "overcome", "overlook", "own",
    "pace", "pain", "panic", "participate", "particular", "party", "patient", "pattern", "pause",
    "peace", "perceive", "perform", "perhaps", "persist", "personal", "persuade", "phase",
    "phenomenon", "physical", "pick", "pilot", "pioneer", "plain", "plan", "plant", "platform",
    "pleasant", "pledge", "plenty", "policy", "political", "poor", "popular", "portion", "positive",
    "possible", "post", "potential", "poverty", "power", "practice", "precious", "predict",
    "prefer", "premise", "prepare", "press", "pressure", "prevent", "previous", "price", "primary",
    "prime", "principal", "principle", "priority", "private", "probably", "process", "produce",
    "professional", "profit", "program", "progress", "project", "prominent", "promise", "promote",
    "propose", "protect", "protest", "prove", "provide", "publish", "purchase", "pursue", "qualify",
    "quarter", "quiet", "radical", "raise", "random", "range", "rapid", "rare", "rate", "reach",
    "react", "read", "real", "realize", "reasonable", "recall", "receive", "recent", "recognize",
    "recommend", "record", "recruit", "reduce", "refer", "reflect", "reform", "regard", "regional",
    "regulate", "reinforce", "reject", "relate", "relative", "release", "relevant", "relief",
    "religion", "remain", "remedy", "remote", "remove", "replace", "reply", "report", "represent",
    "reproduce", "request", "require", "research", "resolve", "resort", "resource", "respond",
    "restore", "restrict", "retain", "reveal", "revolution", "reward", "rid", "rise", "risk",
    "role", "rough", "route", "routine", "rule", "run", "sacrifice", "safety", "salary", "sample",
    "scale", "scene", "schedule", "scholar", "science", "scope", "score", "season", "secure",
    "seek", "select", "senior", "sense", "sensitive", "separate", "sequence", "serve", "session",
    "settle", "shelter", "shift", "ship", "shock", "short", "shoulder", "signal", "significant",
    "silence", "silly", "similar", "simple", "site", "situation", "skill", "smooth", "social",
    "solely", "solve", "somewhat", "source", "special", "species", "specific", "speech", "spirit",
    "spite", "split", "spread", "stable", "staff", "stage", "stake", "standard", "status",
    "steady", "stick", "still", "stimulate", "stock", "strain", "strategy", "strength", "stress",
    "stretch", "strict", "strike", "string", "strong", "structure", "struggle", "style", "subjective",
    "submit", "substance", "succeed", "sufficient", "summer", "supply", "support", "suppose",
    "supreme", "surface", "surplus", "survive", "suspect", "suspend", "sustain", "switch",
    "symbol", "system", "tackle", "target", "task", "technique", "technology", "temperature",
    "temporary", "tend", "tendency", "tense", "theory", "thorough", "threat", "throughout", "thus",
    "tight", "tiny", "tool", "topic", "total", "touch", "tough", "tour", "tower", "track",
    "trade", "traffic", "train", "transfer", "transform", "transition", "transport", "travel",
    "treat", "tremendous", "trend", "trial", "tribe", "troop", "trouble", "unique", "unit",
    "universe", "urban", "urge", "useful", "utter", "various", "venture", "version", "victim",
    "victory", "view", "violate", "virtual", "visible", "vision", "visit", "vital", "volume",
    "vote", "wage", "warn", "welfare", "widespread", "wild", "win", "wind", "wise", "withdraw",
    "witness", "wonder", "wood", "worth", "wound", "writer", "young", "youth"
]
